platform :ios, '18.0'
use_frameworks!
inhibit_all_warnings!

target 'TRIX3DCompanion' do
  # 百度地图 SDK
  pod 'BaiduMapKit', '~> 6.5.0'  # 基础地图 + 定位

  # 可选模块（按需添加）
  # pod 'BaiduMapKit/CloudSearch'  # 云检索
  # pod 'BaiduMapKit/Navigation'  # 导航（需要申请导航功能）
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
    end
  end

  # Create BaiduMapKit umbrella module map that exposes all sub-frameworks
  pods_root = File.join(installer.sandbox.root, 'BaiduMapKit', 'BaiduMapKit')
  umbrella_dir = pods_root
  FileUtils.mkdir_p(umbrella_dir)

  # Write umbrella header
  umbrella_header = File.join(umbrella_dir, 'BaiduMapKit.h')
  File.write(umbrella_header, <<-HEADER)
// BaiduMapKit Umbrella Header
// Re-exports all BaiduMapKit sub-framework headers
#ifndef BaiduMapKit_h
#define BaiduMapKit_h

#import <BaiduMapAPI_Base/BMKBaseComponent.h>
#import <BaiduMapAPI_Map/BMKMapComponent.h>
#import <BaiduMapAPI_Search/BMKSearchComponent.h>
#import <BaiduMapAPI_Utils/BMKUtilsComponent.h>

#endif /* BaiduMapKit_h */
HEADER

  # Write module map
  module_map = File.join(umbrella_dir, 'module.modulemap')
  File.write(module_map, <<-MODULEMAP)
// BaiduMapKit Umbrella Module Map
// Exposes BaiduMapKit as a single module importing all sub-frameworks
module BaiduMapKit {
    umbrella header "BaiduMapKit.h"

    export *
    module * { export * }
}
MODULEMAP

  # Patch BaiduMapKit/Base target to use our modulemap
  installer.pods_project.targets.each do |target|
    if target.name == 'BaiduMapKit'
      target.build_configurations.each do |config|
        config.build_settings['MODULEMAP_FILE'] = module_map
      end
    end
  end

  installer.pods_project.save
end
