platform :ios, '18.0'
use_frameworks!
inhibit_all_warnings!

target 'TRIX3DCompanion' do
  # MapKit is built into iOS - no pod needed
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
    end
  end
end
